<a href="https://colab.research.google.com/github/sametgirgin/Machine-Learning-Classification-Models/blob/master/ANN_Churn_Rate_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd 
import numpy as np 
!pip install -q keras
import keras

In [60]:
from google.colab import files 
uploaded= files.upload()

Saving Churn_Modelling.csv to Churn_Modelling (3).csv


In [0]:
import io 
dataset = pd.read_csv(io.BytesIO(uploaded['Churn_Modelling.csv']))

In [62]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [64]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [0]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [0]:
!pip install -q keras
import keras
from keras.models import Sequential
from keras.layers import Dense

In [0]:
# Initialising the ANN
classifier = Sequential()

In [70]:
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [71]:
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [72]:
classifier.add(Dense(output_dim = 1, init = "uniform", activation="sigmoid"))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [0]:
# Compiling the ANN
classifier.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [75]:
classifier.fit(X_train, y_train, batch_size=10, nb_epoch= 100)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/100
8000/8000 [==============================] - 2s 195us/step - loss: 0.4886 - acc: 0.7956
Epoch 2/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.4296 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.4244 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.4195 - acc: 0.8127
Epoch 5/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.4163 - acc: 0.8237
Epoch 6/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.4141 - acc: 0.8312
Epoch 7/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.4121 - acc: 0.8305
Epoch 8/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.4107 - acc: 0.8324
Epoch 9/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.4098 - acc: 0.8317
Epoch 10/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.4084 - acc: 0.8330

In [0]:
y_pred = classifier.predict(X_test)

In [77]:
y_pred

array([[0.18625706],
       [0.32718825],
       [0.14960188],
       ...,
       [0.1754008 ],
       [0.1933479 ],
       [0.08562708]], dtype=float32)

In [0]:
y_pred = (y_pred > 0.5)

In [79]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [81]:
cm

array([[1552,   43],
       [ 278,  127]])